<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="7OYUE0XO9WRHOLL" name="com.lh.practice.testng.timeOutTest" tests="2" failures="1" timestamp="15 Oct 2018 03:24:08 GMT" time="5.262" errors="0">
  <testcase name="testSuccess" time="2.255" classname="com.lh.practice.testng.timeOutTest"/>
  <testcase name="testUnSuccess" time="3.007" classname="com.lh.practice.testng.timeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testUnSuccess() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testUnSuccess() didn't finish within the time-out 3000
]]>
    </failure>
  </testcase> <!-- testUnSuccess -->
</testsuite> <!-- com.lh.practice.testng.timeOutTest -->
